"""baseline all tables

Revision ID: 24e67a9a0e3c
Revises: 
Create Date: 2026-08-11 15:46:25.158189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e67a9a0e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('owner_id', sa.String(length=36), nullable=False, comment='所有者 user_id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名'),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='env_var | file'),
    sa.Column('target', sa.String(length=255), nullable=False, comment='env_var→环境变量名(大写下划线) / file→容器内文件名(.secrets/<target>)'),
    sa.Column('secret_encrypted', sa.Text(), nullable=False, comment='Fernet 加密的凭据值'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credentials_owner', 'credentials', ['owner_id'], unique=False)
    op.create_index(op.f('ix_credentials_owner_id'), 'credentials', ['owner_id'], unique=False)
    op.create_table('llm_providers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名，如 DeepSeek 官方'),
    sa.Column('provider_type', sa.String(length=30), nullable=False, comment='deepseek | tencent | openai_compat | anthropic | custom'),
    sa.Column('base_url', sa.String(length=512), nullable=False, comment='Anthropic 兼容端点'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False, comment='Fernet 加密的 API Key'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='模型名，如 deepseek-v4-flash'),
    sa.Column('timeout_ms', sa.Integer(), nullable=False, comment='API_TIMEOUT_MS'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为全局默认 Provider'),
    sa.Column('extra', sa.Text(), nullable=False, comment='扩展配置 JSON'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_providers_default', 'llm_providers', ['is_default'], unique=False)
    op.create_index('idx_llm_providers_enabled', 'llm_providers', ['enabled'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='admin | analyst | auditor | viewer'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tasks',
    sa.Column('project_address', sa.String(length=1024), nullable=False, comment='项目地址 (Git URL)'),
    sa.Column('project_ref', sa.String(length=255), nullable=True, comment='分支/commit/tag'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='git | local_upload'),
    sa.Column('vulnerability_description', sa.Text(), nullable=False, comment='漏洞描述'),
    sa.Column('vulnerability_reasoning', sa.Text(), nullable=True, comment='漏洞推理过程'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | queued | running | needs_review | completed | failed | cancelled'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='low | medium | high | critical'),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('credential_refs', sa.Text(), nullable=False, comment='关联凭据 id 的 JSON 数组（P1-6 Credential Proxy）'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_owner_status', 'tasks', ['owner_id', 'status'], unique=False)
    op.create_index('idx_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('task_runs',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | preflight | running | completed | failed | cancelled'),
    sa.Column('agent_session_id', sa.String(length=128), nullable=True, comment='Agent 会话 ID'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='实际开始执行时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='执行完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_runs_task_status', 'task_runs', ['task_id', 'status'], unique=False)
    op.create_index(op.f('ix_task_runs_task_id'), 'task_runs', ['task_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='事件序列号，全局递增'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='phase.updated | tool.call.* | evidence.created | agent.completed | agent.failed'),
    sa.Column('payload', sa.Text(), nullable=False, comment='JSON 事件载荷'),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_events_run_seq', 'agent_events', ['run_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_events_run_id'), 'agent_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_events_task_id'), 'agent_events', ['task_id'], unique=False)
    op.create_table('reports',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | generated | published | archived'),
    sa.Column('conclusion', sa.String(length=20), nullable=False, comment='exists | not_exists | unconfirmed'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True, comment='结论摘要'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='完整分析推理'),
    sa.Column('evidence_summary', sa.Text(), nullable=True, comment='证据摘要（JSON）'),
    sa.Column('artifact_key', sa.String(length=512), nullable=True, comment='报告产物在 MinIO 的 key'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_owner_status', 'reports', ['owner_id', 'status'], unique=False)
    op.create_index('idx_reports_task', 'reports', ['task_id'], unique=False)
    op.create_index(op.f('ix_reports_owner_id'), 'reports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reports_run_id'), 'reports', ['run_id'], unique=False)
    op.create_index(op.f('ix_reports_task_id'), 'reports', ['task_id'], unique=False)
    op.create_table('evidences',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False, comment='MinIO 对象 key'),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False, comment='artifact | log | screenshot | poc'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidences_report', 'evidences', ['report_id'], unique=False)
    op.create_index(op.f('ix_evidences_report_id'), 'evidences', ['report_id'], unique=False)
    op.create_index(op.f('ix_evidences_task_id'), 'evidences', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_task_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_report_id'), table_name='evidences')
    op.drop_index('idx_evidences_report', table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_reports_task_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_run_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_owner_id'), table_name='reports')
    op.drop_index('idx_reports_task', table_name='reports')
    op.drop_index('idx_reports_owner_status', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_agent_events_task_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_run_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_index('idx_agent_events_run_seq', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_task_runs_task_id'), table_name='task_runs')
    op.drop_index('idx_task_runs_task_status', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_index('idx_tasks_status_created', table_name='tasks')
    op.drop_index('idx_tasks_owner_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_llm_providers_enabled', table_name='llm_providers')
    op.drop_index('idx_llm_providers_default', table_name='llm_providers')
    op.drop_table('llm_providers')
    op.drop_index(op.f('ix_credentials_owner_id'), table_name='credentials')
    op.drop_index('idx_credentials_owner', table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
