"""stage1 project node_runs tables task report structured fields

Revision ID: d2d584fe83eb
Revises: 24e67a9a0e3c
Create Date: 2026-08-12 11:28:36.911950
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d584fe83eb'
down_revision: Union[str, None] = '24e67a9a0e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('git_url', sa.String(length=1024), nullable=False, comment='Git URL'),
    sa.Column('default_ref', sa.String(length=255), nullable=True, comment='默认分支/tag'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('detected_language', sa.String(length=50), nullable=True),
    sa.Column('detected_framework', sa.String(length=100), nullable=True),
    sa.Column('is_web', sa.Boolean(), nullable=True),
    sa.Column('last_cloned_at', sa.DateTime(), nullable=True, comment='P2 源码缓存复用用'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_owner', 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_git_url'), 'projects', ['git_url'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('node_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('node_index', sa.Integer(), nullable=False, comment='0-5'),
    sa.Column('node_key', sa.String(length=20), nullable=False, comment='source|profile|env_ready|audit|reproduce|report'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending|running|completed|failed|skipped'),
    sa.Column('input_json', sa.Text(), nullable=False, comment='节点输入(前序 output 组装)'),
    sa.Column('output_json', sa.Text(), nullable=False, comment='节点结构化产出(交接契约)'),
    sa.Column('attempt', sa.Integer(), nullable=False, comment='排障重试计数(节点 2 用,max 5)'),
    sa.Column('agent_session_id', sa.String(length=128), nullable=True, comment='AI 节点 SDK session_id'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_runs_run_idx', 'node_runs', ['run_id', 'node_index'], unique=True)
    op.create_index('idx_node_runs_task_key', 'node_runs', ['task_id', 'node_key'], unique=False)
    op.create_index(op.f('ix_node_runs_run_id'), 'node_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_node_runs_task_id'), 'node_runs', ['task_id'], unique=False)

    # SQLite 不支持 ALTER 加 FK,用 batch mode(copy-move);PG 下 batch 是 no-op 直通
    with op.batch_alter_table('agent_events') as batch_op:
        batch_op.add_column(sa.Column('node_run_id', sa.String(length=36), nullable=True, comment='所属 NodeRun(节点化后,事件归属节点)'))
        batch_op.create_index('ix_agent_events_node_run_id', ['node_run_id'], unique=False)
        batch_op.create_foreign_key('fk_agent_events_node_run', 'node_runs', ['node_run_id'], ['id'])

    with op.batch_alter_table('reports') as batch_op:
        batch_op.add_column(sa.Column('verdict', sa.String(length=30), nullable=True, comment='6 档: confirmed|partial|code_reachable|code_smell|false_positive|not_reproduced'))
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True, comment='Critical/High/Medium/Low/None'))
        batch_op.add_column(sa.Column('vulnerable_file', sa.String(length=1024), nullable=True, comment='漏洞文件定位'))
        batch_op.add_column(sa.Column('report_data', sa.Text(), nullable=True, comment='8 节结构化 JSON(对齐 report_template)'))
        batch_op.add_column(sa.Column('md_artifact_key', sa.String(length=512), nullable=True, comment='MinIO:原始 md key'))
        batch_op.add_column(sa.Column('docx_artifact_key', sa.String(length=512), nullable=True, comment='MinIO:导出 docx key'))
        batch_op.create_index('ix_reports_cvss_score', ['cvss_score'], unique=False)
        batch_op.create_index('ix_reports_verdict', ['verdict'], unique=False)

    with op.batch_alter_table('tasks') as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=36), nullable=True, comment='关联 Project(P1 新增,project_address 保留兼容)'))
        batch_op.add_column(sa.Column('verdict', sa.String(length=30), nullable=True, comment='6 档判定: confirmed|partial|code_reachable|code_smell|false_positive|not_reproduced'))
        batch_op.create_index('ix_tasks_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_tasks_verdict', ['verdict'], unique=False)
        batch_op.create_foreign_key('fk_tasks_project', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_constraint('fk_tasks_project', type_='foreignkey')
        batch_op.drop_index('ix_tasks_verdict')
        batch_op.drop_index('ix_tasks_project_id')
        batch_op.drop_column('verdict')
        batch_op.drop_column('project_id')
    with op.batch_alter_table('reports') as batch_op:
        batch_op.drop_index('ix_reports_verdict')
        batch_op.drop_index('ix_reports_cvss_score')
        batch_op.drop_column('docx_artifact_key')
        batch_op.drop_column('md_artifact_key')
        batch_op.drop_column('report_data')
        batch_op.drop_column('vulnerable_file')
        batch_op.drop_column('severity')
        batch_op.drop_column('cvss_score')
        batch_op.drop_column('verdict')
    op.drop_index(op.f('ix_agent_events_node_run_id'), table_name='agent_events')
    with op.batch_alter_table('agent_events') as batch_op:
        batch_op.drop_constraint('fk_agent_events_node_run', type_='foreignkey')
        batch_op.drop_column('node_run_id')
    op.drop_index(op.f('ix_node_runs_task_id'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_run_id'), table_name='node_runs')
    op.drop_index('idx_node_runs_task_key', table_name='node_runs')
    op.drop_index('idx_node_runs_run_idx', table_name='node_runs')
    op.drop_table('node_runs')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_git_url'), table_name='projects')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
